// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-services/HomeServicesApp.tsx": () => import("../components/mockups/home-services/HomeServicesApp.tsx")
};
